# Load necessary modules
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule mpm_prefork_module modules/mod_mpm_prefork.so

listen 80

        ServerName http://localhost

        ServerAdmin fostersnt@gmail.com
        DocumentRoot /usr/local/apache2/htdocs/public

# Optionally, configure a virtual host
<VirtualHost *:80>
    <Directory /usr/local/apache2/public>
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog logs/error.log
    # CustomLog logs/access.log common
</VirtualHost>
