LoadModule unixd_module modules/mod_unixd.so

# Set the User and Group
User www-data
Group www-data

# Listen on port 80 or specify another port if needed
Listen 80

# Load required modules
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule dir_module modules/mod_dir.so
LoadModule log_config_module modules/mod_log_config.so

ServerName localhost

DocumentRoot /var/www/html/public

<Directory "/var/www/html/public">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

ErrorLog /dev/stderr
CustomLog /dev/stdout combined

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
